"""Add deployment columns

Revision ID: 1441277844d8
Revises: 3645ae842fcd
Create Date: 2026-03-07 15:14:58.872703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1441277844d8'
down_revision: Union[str, None] = '3645ae842fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deployment_link', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('developer_notes', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'developer_notes')
    op.drop_column('projects', 'deployment_link')
    # ### end Alembic commands ###
