"""Add missing client revision notes

Revision ID: f07bce7bec14
Revises: 1441277844d8
Create Date: 2026-03-10 22:04:47.792546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07bce7bec14'
down_revision: Union[str, None] = '1441277844d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('client_revision_notes', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'client_revision_notes')
    # ### end Alembic commands ###
